---
title: "ch4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 4.2.1 横軸時間のプロット

```{r 4.1, collapse=TRUE}
# 前処理
oldpar <- par(no.readonly = TRUE)
par(mfrow = c(2,2)); par(oma = c(0,0,0,0)); par(mar = c(4,4,2,1))

# (a)ナイル川の年間流量
plot(Nile, main = "(a)")

# (b)二酸化炭素濃度
Ryori <- read.csv("CO2.csv")
y_all <- ts(data = Ryori$CO2, start = c(1987, 1), frequency = 12)
y <- window(y_all, end = c(2014, 12))
y_CO2 <- y
plot(y_CO2, main = "(b)")

# (c)英国の四半期ごとのガス消費量
plot(UKgas, main = "(c)")

# (d)非線形モデルから生成した人工的なデータ
load("BenchmarkNonLinearModel.RData")
y_nonlinear <- ts(y)
plot(y_nonlinear, main = "(d)")

par(oldpar)
```

## 4.2.2 ヒストグラムと五数要約

```{r 4.2, collapse=TRUE}

oldpar <- par(no.readonly = TRUE)
par(mfrow = c(2,2)); par(oma = c(0,0,0,0)); par(mar = c(4,4,2,1))

# (a)ナイル川
hist(Nile, main ="(a)", xlab = "データの値")
summary(Nile)

# (b)二酸化炭素濃度
hist(y_CO2, main = "(b)", xlab = "データの値")
summary(y_CO2)

# (c)英国の四半期ごとのガス消費量
# 対数変換
UKgas_log <- log(UKgas)
hist(UKgas_log, main = "(c)", xlab = "データの値")
summary(UKgas_log)

# (d)非線形モデルから生成した人工的なデータ
hist(y_nonlinear, main = "(d)", xlab = "データの値")
summary(y_nonlinear)

par(oldpar)

```

```{r 4.3, collapse=TRUE}
# (b)NAの位置を特定

NA.point <- which(is.na(y_CO2))

y_CO2[NA.point] <- (y_CO2[NA.point - 1] + y_CO2[NA.point + 1]) / 2

```

## 4.2.3 自己相関係数

```{r 4.4, collapse=TRUE}
# 【自己相関係数】

oldpar <- par(no.readonly = TRUE)
par(mfrow = c(2,2)); par(oma = c(0,0,0,0)); par(mar = c(4,4,3,1))

# (a)
acf(Nile, main = "(a)")

# (b)
acf(y_CO2, main = "(b)")

# (c)
acf(UKgas_log, main = "(c)")

# (d)
acf(y_nonlinear, main = "(d)")

par(oldpar)

```

### 周波数領域展開

```{r 4.5, collapse=TRUE}
# 周波数領域変換

plot.spectrum <- function(dat, lab = "", main ="", y_max = 1, tick = c(8,4), unit = 1) {
  # データの周波数領域変換
  dat_FFT <- abs(fft(as.vector(dat)))
  
  # グラフ横軸
  data_len <- length(dat_FFT)
  freq_tick <- c(data_len , tick ,2)
  
  # データのプロット
  plot(dat_FFT / max(dat_FFT), type = "l", main = main, ylab = "|規格化後の周波数スペクトル|" , ylim = c(0, y_max), xlab = sprintf("周波数[1/%s]", lab), xlim = c(1, data_len / 2), xaxt = "n")
  axis(side = 1, at = data_len / freq_tick * unit + 1, labels = sprintf("1/%d", freq_tick), cex.axis = 0.7)
}

oldpar <- par(no.readonly = TRUE)
par(mfrow = c(2,2)); par(oma = c(0,0,0,0)); par(mar = c(4,4,3,1))

# (a)
plot.spectrum(Nile, lab = "年", main = "(a)")

# (b)
plot.spectrum(y_CO2, lab = "月", main = "(b)", tick = c(12, 6))

# (c)
plot.spectrum(UKgas_log, lab = "月", main = "(c)", tick = c(12, 6), unit = 3)

# (d)
plot.spectrum(y_nonlinear, lab = "時点", main = "(d)")

par(oldpar)
```

## 4.5 フィルタリング・予測・平滑化

```{r 4.6 collapse=TRUE}
# ホルト・ウィンタース法

# (a) 
HW_Nile <- HoltWinters(Nile, beta = FALSE, gamma = FALSE)
str(HW_Nile)

# (b)
HW_CO2 <- HoltWinters(y_CO2)

# (c)
HW_UKgas_log <- HoltWinters(UKgas_log)

# (d)
HW_nonlinear <- HoltWinters(y_nonlinear, gamma = FALSE)

# フィルタリング値の描画
oldpar <- par(no.readonly = TRUE)
par(mfrow = c(2,2)); par(oma = c(0,0,0,0)); par(mar = c(4,4,3,1))
mygray <- "#80808080"

plot(HW_Nile, main = "(a)", col = mygray, col.predicted = "black", lty.predicted = "dashed")
plot(HW_CO2, main = "(b)", col = mygray, col.predicted = "black", lty.predicted = "dashed")
plot(HW_UKgas_log, main = "(c)", col = mygray, col.predicted = "black", lty.predicted = "dashed")
plot(HW_nonlinear, main = "(d)", col = mygray, col.predicted = "black", lty.predicted = "dashed")

par(oldpar)
```


```{r 4.7 collapse=TRUE}
# ホルト・ウィンタース法（成分ごと）

# (a)
HW_out <- HW_Nile
HW_decomp <- ts.union(y = HW_out$x,
                      Level = HW_out$fitted[, "level"],
                      Resisuals = residuals(HW_out))
plot(HW_decomp, main = "")

# (b)
HW_out <- HW_CO2
HW_decomp <- ts.union(y = HW_out$x,
                      Level = HW_out$fitted[, "level"] + HW_out$fitted[, "trend"],
                      Season = HW_out$fitted[, "season"],
                      Resisuals = residuals(HW_out))
plot(HW_decomp, main = "")

# (c)
HW_out <- HW_UKgas_log
HW_decomp <- ts.union(y = HW_out$x,
                      Level = HW_out$fitted[, "level"] + HW_out$fitted[, "trend"],
                      Season = HW_out$fitted[, "season"],
                      Resisuals = residuals(HW_out))
plot(HW_decomp, main = "")

# (d)
HW_out <- HW_nonlinear
HW_decomp <- ts.union(y = HW_out$x, 
                      Level = HW_out$fitted[, "level"] + HW_out$fitted[, "trend"], 
                      Resisuals = residuals(HW_out))
plot(HW_decomp, main = "")
```

```{r 4.8 collapse=TRUE}
# ホルト・ウィンタース法（予測）

# (b)
HW_predict <- predict(HW_CO2, n.ahead = 12)
str(HW_predict)

# 観測値・フィルタリング値と予測値を合わせて描画
plot(HW_CO2, HW_predict, main = "ホルト・ウィンタース法によるフィルタリングと予測", col = mygray, col.predicted = "black", lty.predicted = "dashed")

# 2015年の観測値も描画
y_CO2_2015 <- window(y_all, start = 2015)
lines(y_CO2_2015, col = mygray)

```

## 4.6 結果の吟味

```{r 4.9 collapse=TRUE}
# 残差の自己相関
oldpar <- par(no.readonly = TRUE)
par(mfrow = c(2,2)); par(oma = c(0,0,0,0)); par(mar = c(4,4,3,1))

acf(residuals(HW_Nile), main = "(a)")
acf(residuals(HW_CO2), main = "(b)")
acf(residuals(HW_UKgas_log), main = "(c)")
acf(residuals(HW_nonlinear), main = "(d)")

par(oldpar)

```

```{r 4.10 collapse=TRUE}
# 予測性能

# 平均絶対誤差率
MAPE <- function(true, pred) {
  mean(abs(pred - true) / true)
}

MAPE(true = y_CO2_2015, pred = HW_predict)

```